Middleware user auth
alkemyTech/OT268-server pull request #20
Opened 2022-08-24 17:08 UTC by Jmoreyra93

Middleware para usuarios autenticados. 
-Verificar si la petición contiene token caso contrario devuelvo un error 403

2022-08-24 20:36 UTC, kevinderitis requested changes

2022-08-24 20:36 UTC, kevinderitis commented on middlewares/user/userAdmin.js
> +const jwt = require('jsonwebtoken');
Tenemos dos carpetas dentro de middlewares /user y /userAdmin. Cual es la diferencia? Los archivos que tienen dentro tienen nombre similares? que proposito cumplen?

2022-08-24 22:11 UTC, Jmoreyra93 commented on middlewares/user/userAdmin.js
> +const jwt = require('jsonwebtoken');
Ninguna diferencia, revisando el codigo puse el mismo codigo. Creo haberlo resuelto ahora

2022-08-25 13:17 UTC, kevinderitis commented
Debe apuntar a development.

2022-08-25 19:34 UTC, closed without merging