Ot268 end point detail category card43
alkemyTech/OT268-server pull request #29
Opened 2022-08-27 12:46 UTC by egsta

2022-08-30 13:30 UTC, kevinderitis requested changes

2022-08-30 13:30 UTC, kevinderitis commented on middlewares/checkRol/checkRol.js
> +const checkRolDev = (req, res, next) => {
Eliminar esto, no debe ir en el PR.

2022-08-30 20:03 UTC, egsta commented on middlewares/checkRol/checkRol.js
> +const checkRolDev = (req, res, next) => {
Delete Done

2022-08-31 13:20 UTC, kevinderitis requested changes

2022-08-31 13:20 UTC, kevinderitis commented on controllers/category.controller.js
>  const get =  async (req,res) =>{
Cambiar nombre, fijarse como estan el resto de los controller.

2022-08-31 19:32 UTC, kevinderitis approved these changes

2022-08-31 19:33 UTC, kevinderitis commented
Corregir conflictos

2022-08-31 20:13 UTC, merged