Ot268 end point post category card44
alkemyTech/OT268-server pull request #30
Opened 2022-08-27 13:21 UTC by egsta

Adding endpoint post to category, with verfication of field name as string not null

2022-08-30 13:31 UTC, kevinderitis requested changes

2022-08-30 13:31 UTC, kevinderitis commented on middlewares/checkRol/checkRol.js
> +const checkRolDev = (req, res, next) => {
Eliminar esto, no debe ir en el PR.

2022-08-30 20:03 UTC, egsta commented on middlewares/checkRol/checkRol.js
> +const checkRolDev = (req, res, next) => {
Delete done

2022-08-31 13:22 UTC, kevinderitis requested changes

2022-08-31 13:22 UTC, kevinderitis commented on controllers/category.controller.js
>  const get =  async (req,res) =>{
Mismo que en otros PR. Cambiar nombre.

2022-08-31 19:33 UTC, kevinderitis commented
Corregir conflictos

2022-08-31 20:16 UTC, kevinderitis approved these changes

2022-08-31 20:16 UTC, merged