Ot268 25/user register endpoint
alkemyTech/OT268-server pull request #4
Opened 2022-08-19 22:37 UTC by sebitacasa

2022-08-24 20:34 UTC, kevinderitis requested changes

2022-08-24 20:34 UTC, kevinderitis commented on controllers/register.controller.js
> +      if (!firstName &&!lastName && !email && !password && !image) {
En vez de realizar esta validación, podrias utilizar el modelo de User para poder hacer las validaciones necesarias con respecto a los campos que necesitas.

2022-08-24 20:34 UTC, kevinderitis commented on controllers/register.controller.js
> +      if (!firstName &&!lastName && !email && !password && !image) {
Por el momento podrias utilizarlo asi, pero luego se podria mejorar.

2022-08-24 20:34 UTC, kevinderitis commented on routes/auth.js
> +    check('email').notEmpty().isEmail().withMessage({ ok: false }),
Podriamos crear funciones para hacer estas validaciones en las rutas.

2022-08-24 20:34 UTC, kevinderitis commented on routes/users.js
> +router.route("/auth/register").post(register)
Respetar la misma sintaxis que el resto de las rutas.

2022-08-24 20:34 UTC, kevinderitis commented on routes/users.js
> +var express = require("express");
Cambiar var por const o let segun corresponda.

2022-08-24 20:48 UTC, sebitacasa commented on controllers/register.controller.js
> +      if (!firstName &&!lastName && !email && !password && !image) {
perfecto, lo voy a implementar para la proxima

2022-08-24 20:49 UTC, sebitacasa commented on routes/users.js
> +router.route("/auth/register").post(register)
perfecto, tambien lo voy a modificar para la proxima

2022-08-24 20:50 UTC, sebitacasa commented on routes/auth.js
> +    check('email').notEmpty().isEmail().withMessage({ ok: false }),
esa funcion no la realice yo

2022-08-24 20:51 UTC, sebitacasa commented on routes/users.js
> +var express = require("express");
normalmente pongo const, pero parece que no me di cuenta y deje el que viene por defecto, lo voy a tener en cuenta.

2022-08-26 13:23 UTC, kevinderitis requested changes

2022-08-26 13:23 UTC, kevinderitis commented on bin/www
> + var app = require('../app');
Cambiar los var y usar let y const segun corresponda.

2022-08-26 13:23 UTC, kevinderitis commented on routes/users.js
> -var router = express.Router();
Cambiar var.

2022-08-26 13:47 UTC, kevinderitis approved these changes

2022-08-26 13:47 UTC, merged