Ot268 19/model migration controller categories
alkemyTech/OT268-server pull request #5
Opened 2022-08-20 15:55 UTC by egsta

Create a model migration controller from category

2022-08-23 13:46 UTC, kevinderitis requested changes

2022-08-23 13:46 UTC, kevinderitis commented on controllers/category.controller.js
> +exports.get =  async (req,res) =>{
En realacion con el resto de los archivos que hay en el mismo PR, estaria bueno hacer los export todos juntos al final.

2022-08-23 13:46 UTC, kevinderitis commented on controllers/category.controller.js
> +    console.log("llego DeleteById ", Prueba)
Acordarse de eliminar los  console.log a menos que sea para testear algo en dev.

2022-08-23 13:46 UTC, kevinderitis commented on middelwares/validation/schemaValidation.js
> +exports.checkSchema = ( req, res, next, keys) => {
Mismo comentario con respecto a exports.

2022-08-23 13:46 UTC, kevinderitis commented on routes/category.js
> +    const keys = ["name", "image", "description"];
Estas validaciones se deberian agregar en un middleware e implementarlo en la ruta que sea necesaria.

2022-08-23 13:46 UTC, kevinderitis commented on routes/category.js
> +    const keys = ["name", "image", "description"];
Mismo que antes.

2022-08-23 14:49 UTC, egsta commented on controllers/category.controller.js
> +exports.get =  async (req,res) =>{
Se cambia forma de exportar funciones

2022-08-23 14:49 UTC, egsta commented on controllers/category.controller.js
> +    console.log("llego DeleteById ", Prueba)
se borran los log

2022-08-23 14:50 UTC, egsta commented on middelwares/validation/schemaValidation.js
> +exports.checkSchema = ( req, res, next, keys) => {
se quita schemavalidation por redundante

2022-08-23 14:51 UTC, egsta commented on routes/category.js
> +    const keys = ["name", "image", "description"];
se quita schemavalidation por redundante

2022-08-23 14:51 UTC, egsta commented on routes/category.js
> +    const keys = ["name", "image", "description"];
se quita schemavalidation por redundante

2022-08-24 13:27 UTC, kevinderitis approved these changes

2022-08-24 13:28 UTC, merged