Ot268 authentication rol template mail card28 card31
alkemyTech/OT268-server pull request #6
Opened 2022-08-20 16:06 UTC by egsta

Add check roleId and TemplateMail

2022-08-24 13:21 UTC, kevinderitis requested changes

2022-08-24 13:21 UTC, kevinderitis commented on middelwares/checkRol/checkRol.js
> +module.exports = function checkRol(req, res, next){
Almacenar funcion en una variables y luego exportarla, esto ayuda si en algun momento queremos agregar otra function para exportar.

2022-08-24 13:21 UTC, kevinderitis commented on middelwares/checkRol/checkRol.js
> +            res.sendStatus(401);
Se podria adjuntar un mensaje con el codigo de error para saber que es lo que fallo en el middleware.

2022-08-24 13:42 UTC, egsta commented on middelwares/checkRol/checkRol.js
> +module.exports = function checkRol(req, res, next){
Cambio a formato de variable

2022-08-24 13:42 UTC, egsta commented on middelwares/checkRol/checkRol.js
> +            res.sendStatus(401);
Se agrega msg por error

2022-08-26 13:30 UTC, kevinderitis approved these changes

2022-08-26 13:31 UTC, merged