Ot268 86 agregar paginaciona categorias
alkemyTech/OT268-server pull request #75
Opened 2022-09-09 21:58 UTC by egsta

2022-09-13 01:45 UTC, kevinderitis requested changes

2022-09-13 01:45 UTC, kevinderitis commented on controllers/category.controller.js
> +    paginationCategory
Que seria paginationCategory?

2022-09-13 01:45 UTC, kevinderitis commented on controllers/category.controller.js
> +        Category.findAll({limit: 10, offset: (page - 1) * 10}).then(response => {
Se podria agregar el limit tambien, es opcional. Despues podemos charlarlo.

2022-09-13 12:27 UTC, egsta commented on controllers/category.controller.js
> +    paginationCategory
Deleted

2022-09-13 12:27 UTC, egsta commented on controllers/category.controller.js
> +        Category.findAll({limit: 10, offset: (page - 1) * 10}).then(response => {
Ok

2022-09-14 13:25 UTC, kevinderitis approved these changes

2022-09-14 13:25 UTC, merged