add pagination Testimonials and other fix
alkemyTech/OT268-server pull request #87
Opened 2022-09-15 21:15 UTC by Jmoreyra93

Cuando realizo la petición get a /testimonials , la misma de devuelve una paginación con 10 elementos y las url back y next. Que contiene la URL para para redireccionarme a la siguiente pagina.

2022-09-21 13:37 UTC, kevinderitis requested changes

2022-09-21 13:37 UTC, kevinderitis commented on routes/testimonials.js
> +router.post('/', createTestimonials );
Agregar middleware.

2022-09-21 13:51 UTC, Jmoreyra93 commented on routes/testimonials.js
> +router.post('/', createTestimonials );
Ya resolvi los conflictos, y agregue el middleware a la petición post

2022-09-22 13:13 UTC, kevinderitis approved these changes

2022-09-22 13:13 UTC, merged